export const RESET_TOKEN_BYTES = 32;
export const RESET_TOKEN_EXPIRY_MINUTES = 45;
export const RESET_RESEND_COOLDOWN_SECONDS = 60;
export const RESET_MAX_SENDS_PER_EMAIL_PER_HOUR = 3;
export const RESET_MAX_SENDS_PER_IP_PER_HOUR = 10;
